### ISSUE TITLE
Test fails at `setUp()`

### ISSUE THREAD

**Issue by PraneshASP** [huff-language/foundry-huff#1]
Hi,
First, thanks for this template that uses foundry for building and testing huff contracts.

However, I ran into the following issue when I tried to run the tests.

```sh
Running 1 test for src/test/HuffDeployer.t.sol:HuffDeployerTest
[FAIL. Reason: Setup failed: No such file or directory (os error 2)] setUp() (gas: 0)
Test result: FAILED. 0 passed; 1 failed; finished in 1.88ms

Failed tests:
[FAIL. Reason: Setup failed: No such file or directory (os error 2)] setUp() (gas: 0)

Encountered a total of 1 failing tests, 0 tests succeeded
```

Steps to reproduce:
- Clone the repo
- Run `forge install`
- Run `forge build` (to make sure there are no compilation errors)
- Run `forge test`

**Comment by abigger87** [comment]
Fixed in upgrade to [huff-rs](https://github.com/huff-language/huff-rs)
